version: '3.9'

services:

  my-service:
    image: traefik/whoami
    environment:
      - WHOAMI_NAME=my-service.local
      - WHOAMI_PORT_NUMBER=8080
    expose:
      - "8080"

  reverse-proxy:
    image: nginx:latest
    ports:
      - "{{ HTTP_PORT }}:80"
      - "{{ HTTPS_PORT }}:443"
    volumes:
      - ./nginx-conf/:/etc/nginx/conf.d/:ro
      - ./nginx-certbot/www/:/var/www/certbot/:ro
      - ./nginx-cert/:/etc/letsencrypt/:ro
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx-certbot/:/var/www/certbot/:rw
      - ./nginx-cert/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
